services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      retries: 4
  config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
     discovery-service:
        condition: service_healthy
  role-service:
    build: ./role-service
    container_name: role-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
#  user-service:
#    build: ./user-service
#    container_name: user-service
#    ports:
#      - '8081:8081'
#    expose:
#      - '8081'
#    environment:
#      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
#      - CONFIG_SERVICE_URL=http://config-service:9999
#    depends_on:
#      user-service:
#        condition: service_healthy
#  enset-gateway-service:
#    build: ./gateway-service
#    container_name: enset-gateway-service
#    ports:
#      - '8888:8888'
#    expose:
#      - '8888'
#    environment:
#      - DISCOVERY_SERVICE_URL=http://enset-ebank-discovery-service:8761/eureka
#      - CONFIG_SERVICE_URL=http://enset-ebank-config-service:9999
#    depends_on:
#      enset-ebank-config-service:
#        condition: service_healthy
#  front-send-angular:
#    build: ./angular-front-end
#    container_name: front-send-angular
#    ports:
#      - '82:80'
#    expose:
#      - '82'